FROM ubuntu
RUN apt-get update && apt-get install -y python-pip  && apt-get install -y python-pika && apt-get install -y vim && apt-get install -y iputils-ping &&  apt-get install -y net-tools

WORKDIR /usr/local/bin

#COPY consumer.py .
#CMD ["consumer.py", "-OPTIONAL_FLAG"]